version: "3.2"
services:
    squid:
        image: ubuntu/squid:latest
        deploy:
            mode: replicated
            replicas: 4
            restart_policy:
               condition: any
               max_attempts: 3
               window: 120s
            resources:
                limits:
                    memory: 512m
#        healthcheck:
#            # es necesario tener curl instalado
#            test: curl -sSf --proxy http://$$HOSTNAME:3128 -o /dev/null http://google.com || exit 1
#            interval: 60s
#            timeout: 5s
        environment:
            - TZ=Europe/Madrid
            - SERVICE_NAME={{.Service.Name}}
        ports:
            - 8080:3128
