version: '3.8'

services:
    rsyslog:
        image: $REGISTRY:5000/rsyslog:$TAG
        entrypoint: /docker-entrypoint.sh
        configs:
            - source: rsyslog
              target: /etc/rsyslog.conf
        ports:
            - "514:514/tcp"
            - "514:514/udp"
        volumes:
            - /var/log/rsyslog:/var/log
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
               condition: any
               max_attempts: 3
               window: 120s
            resources:
                limits:
                    memory: 512m
            placement:
                constraints:
                    - node.ip == $IP_REGISTRY
        environment:
            - TZ=Europe/Madrid
            - SERVICE_NAME={{.Service.Name}}

configs:
    rsyslog:
        file: ./config/rsyslog.conf

        
  