apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 4
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: docker.io/ubuntu/squid:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3128
        resources:
          limits:
            memory: 512Mi
        env:
        - name: TZ
          value: "Europe/Madrid"
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: squid-config-volume
          mountPath: /etc/squid/conf.d/squid.conf
          subPath: squid.conf
      volumes:
      - name: squid-config-volume
        configMap:
          name: squid-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
data:
  squid.conf: |
    # Logs
    # ====

    logformat customlog   %>a %[ui %[un %{%Y/%m/%d-%H:%M:%S}tl.%03tu "%rm %ru HTTP/%rv" %>Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh
    access_log daemon:/var/log/squid/access.log customlog

---
apiVersion: v1
kind: Service
metadata:
  name: squid-service
spec:
  type: NodePort
  selector:
    app: squid
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
      nodePort: 30080
