version: "3.8"
services:
    squid:
        image: $REGISTRY:5000/squid:$TAG
        configs:
            - source: squid-custom
              target: /etc/squid/conf.d/squid-custom.conf
        deploy:
            mode: replicated
            replicas: 4
            restart_policy:
               condition: any
               max_attempts: 3
               window: 120s
            resources:
                limits:
                    memory: 512m
        healthcheck:
            test: curl -sSf --proxy http://$$HOSTNAME:3128 -o /dev/null http://google.com || exit 1
            interval: 60s
            timeout: 5s
        environment:
            - TZ=Europe/Madrid
            - SERVICE_NAME={{.Service.Name}}
        ports:
            - 8080:3128
        logging:
            driver: syslog
            options:
                syslog-address: "udp://$RSYSLOG_SERVER:514"
                syslog-facility: "local0"
                syslog-format: "rfc5424"

configs:
    squid-custom:
        file: ./config/squid-custom.conf
